# Use an official Node runtime as the base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy both package.json and package-lock.json
COPY package*.json ./

# Install NestJS dependencies and testing libraries
RUN npm install
RUN npm install --save-dev @nestjs/testing

# Bundle your source code inside the Docker image
COPY . .

# Command to run the tests
CMD [ "npm", "test" ]